# Schema for the configuration files of the Gin theme.
gin.settings:
  type: theme_settings
  label: 'gin settings'
  mapping:
    preset_accent_color:
      type: string
      label: 'Preset accent color'
    preset_focus_color:
      type: string
      label: 'Preset focus color'
    enable_darkmode:
      type: boolean
      label: 'The dark mode'
    classic_toolbar:
      type: string
      label: 'The classic toolbar'
    icon_default:
      type: boolean
      label: 'Use default logo'
    icon_path:
      type: string
      label: 'Path to custom logo'
    high_contrast_mode:
      type: boolean
      label: 'High contrast mode'
    accent_color:
      type: string
      label: 'The accent color'
    focus_color:
      type: string
      label: 'The focus color'
    icon_upload:
      type: string
      label: 'The icon upload'
    show_user_theme_settings:
      type: boolean
      label: 'Let user override theme'
    third_party_settings:
      type: mapping
      label: 'Third party settings'
      mapping:
        shortcut:
          type: mapping
          label: 'Shortcut'
          mapping:
            module_link:
              type: boolean
              label: 'Module Link'
